import type { InferGetStaticPropsType, NextPage } from 'next'
import Link from 'next/link'
import { client } from '../src/libs/client'
import Head from 'next/head'
import { Header } from '../src/_core/components/Header'
import { Footer } from '../src/_core/components/Footer'

export const getStaticProps = async () => {
  const blog = await client.get({ endpoint: 'blog' })
  return {
    props: {
      blogs: blog.contents,
    },
  }
}

const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({ blogs }) => {
  console.log(blogs)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div>
        <ul>
          {blogs.map((blog: any) => (
            <li key={blog.id}>
              <Link href={`/blog/${blog.id}`}>{blog.title}</Link>
            </li>
          ))}
        </ul>
      </div>
      <Footer />
    </>
  )
}

export default Home
